const replaceLR = chaine => {
    let x = chaine.replace(/\n/g, ",");
    x = x.split(",");
    //x = JSON.parse("[" + "," + "]");
    return x;
  };
  
  const findBoxes = inputArray => {
	let candidate = [];

	for (let i = 0; i < inputArray.length; i++) {
		for (let j = i + 1; j < inputArray.length; j++) {
			let can = inputArray[i];
			let t = inputArray[j];
			let diff = 0;
			let index = -1;
			for (let k = 0; k < can.length; k++) {
				if (can[k] !== t[k]) {
					diff++;
					index = k;
					if (diff > 1) break;
				}
			}
			if (diff === 1) {
				candidate.push(can);
				candidate.push(t);
				candidate.push(index);
			}
		}
	}
	let result = candidate[0].split('');
	result.splice(candidate[2], 1);
	return result.join('');
};
  
  let expl=`oeambtcgjqnzhgkdylfapoiusr
  oewmbtcxjqnzhgvdyltapvqusr
  oewmbtchjqnzigkdylfapviuse
  oeimbucxjqnzhgkdyyfapviusr
  fewmbtcxjqndhgcdylfapviusr
  oevgbtccjqnzhgkdylfapviusr
  oewmbtcxjqnzhnkdylmapvpusr
  oewmbtcxjqnzhxkdyldapvirsr
  oewmutccjqnzngkdylfapviusr
  oewmbtcxbqnzhgkdsliapviusr
  ozwmbtfxjqnzcgkdylfapviusr
  oewmbtdxjqnzhgkdypfapsiusr
  oeylbtcxjqnzhgyyylfapviusr
  oewmbtcxjqnzhgkdrlfakuiusr
  oewmbtcujqnxhgkdylfadviusr
  oewmbtcxlqpzhgkdylfaaviusr
  oewmztcxjqnzhgkdylfqpliusr
  oeembtcxjqnzhgkdtlmapviusr
  onwmbtcxjqnqhgkdylfapdiusr
  oewmbtcxnqnzhgkdylfapsbusr
  oeoibtjxjqnzhgkdylfapviusr
  oxwmbtcxjqnzhgkdylfapcipsr
  oewmbtoxbqnzhgzdylfapviusr
  okwubtcxjqnzhgkdylfapiiusr
  oewmbtcxjqnzhgodylfapnicsr
  oewmitcxjqnzhgkdylfaphlusr
  oewmbtaxjqnzhgkhylfapveusr
  oewmftcbjqnzhgkdylfapviurr
  oewmbtcujqnzbgkdylfapliusr
  oeevbtcxjqnzhgkdylfapniusr
  oewmbtcxjqnvhgkdylfapnpusr
  oewabtcxjqnzhgddylfapviust
  oewmbtyxjqnzhgkdvlfapvinsr
  jewmbtcxjonzhzkdylfapviusr
  oewmbrcxjqnzxgkdylfapoiusr
  dewmbtmxjqnzhgkdyvfapviusr
  oewmbtctjqnzhgkdmlfapvihsr
  oewmbjcxjqnzhgvdylfapviurr
  oewmbtcxjqnzhgcdxlfapvfusr
  oewmbucxjqnzhgkdyltapvifsr
  gewmbtcejqezhgkdylfapviusr
  oewebtcxjznzhgkdylfapvhusr
  oewmjtcxjqnzhgkdycfakviusr
  oewmbtcxjtnvhgkdylfabviusr
  oewmbtcxjqnthgkgclfapviusr
  hewmbtcxjqnzhgkdwlfapziusr
  oewmbtcxjqnzhgkdylfqpviysf
  oewmbtcxjvnzhgmdylfapviuse
  oewmbtcxjqnphgkdymzapviusr
  oewmbtcxjqnzwmkdylfapvbusr
  oewmbthxjqnzhgkdylfatvilsr
  oewmbtcxaznzhgkhylfapviusr
  zewmbscxjqnzhgkdylfatviusr
  oewmbecyaqnzhgkdylfapviusr
  oewmbtnxjqnzhekxylfapviusr
  oewmbtcxjqczhgkdyltnpviusr
  yewmbecxjnnzhgkdylfapviusr
  oewmbocxjqnzhgkyylfapviusv
  oewmxtcxjqnzhgkkylfspviusr
  oiwmbtcxjqnzhgkdydfapvgusr
  oewmbtcxjqnzngydylfwpviusr
  oewmctcxjqnzhgkdelfapviasr
  oewmbtcxjqnzhgxdwmfapviusr
  oewmntcxjqnzhgkdylfamviusw
  oewmatcxjqbzhgkdylfapvhusr
  oewmbtcxjqnqhmkdyluapviusr
  opwmbtcxjqnzhgkdywfapvilsr
  omwmbtcxjqnlhgkdylyapviusr
  oewmltcxoqnzhgkdylfapvfusr
  oewmbtcxjqtzhgkdyyoapviusr
  oewmbtcxjqnzhrkdzlffpviusr
  oewmbtqxyqnzhgkdylfalviusr
  oeuzbtcxlqnzhgkdylfapviusr
  oewmbtcxjqnzhtxdylflpviusr
  oewmdtfxjqnzhgkdylfapviufr
  ojwmbtcxjqnzhgkdylfypviqsr
  oewmbtcxjqnzhgkdylfapvivuf
  oewmjtcsjqnzxgkdylfapviusr
  ohembtcxjqnzhnkdylfapviusr
  oewmptcajqnzhgkdylfapviusd
  oewmbtcxjcnwhgkbylfapviusr
  oewmbtcxjqnzhgddnlfapvqusr
  oewmbtcfjqnzhgkdypfapvzusr
  oewdbtccjqnzhgfdylfapviusr
  oewmbtcxjpnzhgkdplfaqviusr
  oepmbhcxjqnzhgkdylfaaviusr
  oewmbtcwjqxzhgkwylfapviusr
  oewmatcxjqnchgkdylfapvifsr
  omwmbncxjqnzhgkdylfapviuyr
  sewmbsckjqnzhgkdylfapviusr
  oewubtcxjqnzhgkdyluapvausr
  ohwmbtcxqqhzhgkdylfapviusr
  oewmbtcxjqnzhgkpylfapnissr
  eewmbccxjqnzhgkdylbapviusr
  oewmitcyjqnzhgkdylkapviusr
  oewmbtcxjvnzhgkdyjfvpviusr
  oewmbtcxjqmzhgkdyefagviusr
  oewmbtcvjqnzhgkdylpapviufr
  oewmbtcxjrnkhgkdylfapsiusr
  oewmbtcxjqnzygkdylfaxvipsr
  oexmbtcxjqczhgkdyloapviusr
  oewmbtcxjqnlhtkdylfapvmusr
  oewmbtcxdqjzdgkdylfapviusr
  oewmbtclgqnzhgkdylfabviusr
  oewmbtvfjqnzhgkdylfapviulr
  oewmbtcxjqnzhgkdyllarvijsr
  oewmbtyxjqnzhgpdylxapviusr
  oeylbtcxjqnzhgkyylfapviusr
  oewmbtctjqnzhjkdylfapviulr
  oermatcxjqnzhgkdylzapviusr
  oewmbtcxjqnztgkdzlfapviutr
  oewlbtcxjqnztgkvylfapviusr
  oewmbtcxjqzvhgkdylfapviusk
  oewmbtcxjqnzmgkdyldapvilsr
  felmbtcxjqnzhgkdylfapviusl
  oewmbtcxjgnzhgkjylfaeviusr
  ovwmbtcxjqpzhgkdylfapvizsr
  eewmbtcpjqnzhgkdylfapvijsr
  oewmbzcxjqnzhgkdylfaeviutr
  tewmbtcljqhzhgkdylfapviusr
  oewmbtcujqnzhgkdnliapviusr
  oewmbtcljqnzhskdylfapvgusr
  oewmbtchjqnzhgkdylmapviuse
  oewmbtcxjqnzbgkdylfaiviurr
  oewmbtcxjqnzhkkdyloapsiusr
  oewjbtcxjqnhhgkdylfapjiusr
  odwmbtcnjqnzhgkdylfapvicsr
  oewmbccxjqrzwgkdylfapviusr
  kewmbtcvjqnzhgkdylaapviusr
  okwmbtcxjqnzhgkdylfspvausr
  oewmbtcxjynzhgkdyafapviusw
  oewmbtcxjqnzhgwdyleayviusr
  oewmbtcxjqnzhgkdylfapviicl
  oewmbtcxjqnzhgkdyltaeziusr
  oewmbtcxrqnzhgkdylftpvizsr
  oewsrtcgjqnzhgkdylfapviusr
  oewmbtsxgqnzhgxdylfapviusr
  oewmbtcxjanzhgtdylfapeiusr
  oewybtcgjqnzhgkdylfapviust
  ojwmbncxjqnzhgkdylfapgiusr
  ocgebtcxjqnzhgkdylfapviusr
  oejcbtcxjqnzhgkvylfapviusr
  oswmbtcxjqnkhgkdylfapviusb
  oewdbtcxjqnzdgkdylfypviusr
  oawmutcxjqnzhgkddlfapviusr
  oewzbtcxyqnzhgkdylfapviusy
  zewmbtcxjqnzkgkdylwapviusr
  aewmbtkxjqnzhgkdylfapviuer
  oewmbtcxwqnzhgkdyofapviuur
  oewmbtcxjqnzggkdylfapanusr
  oewmstcxuqnzhgkdylzapviusr
  zewmbtcxjqozhgkdelfapviusr
  oewzbtcxjqnahgkdyllapviusr
  fewmatcxjqnghgkdylfapviusr
  oewmbtcxjqnzhgkdylfapviyqb
  oewwbtcxjqnzhgkdyljapviqsr
  oewmbtbxjqnzhgkxylfapviesr
  oewmbtcbjqnphgkdylfapviysr
  oewabtcxyqnzhgkdylfabviusr
  oewmbtcxhknzhgkdylfapviusd
  ozwmbtcljqnzhgkdylfapviksr
  tewmbtcxjqnzhgkdylfaxvqusr
  oewmbtcxrqnzhgkdytfapvrusr
  ohwmbtcxjcnzhgkdyifapviusr
  oewmbpcxjqnzhwkdylfaphiusr
  oedmbtcxjqnzhgnbylfapviusr
  oewmbocxjqnehgkdylfapvbusr
  oeymbtcxjqezegkdylfapviusr
  oewmbtcxjqnzhgkdllferviusr
  oewmbtcxjqnzhgkwmlfawviusr
  oewmbtcxienzhgkdyzfapviusr
  mewmbtcxjqnzhqkdylfapviwsr
  oewmbtcxjqnztgkmylfapvdusr
  ouwmbtcxjqnzhokdylpapviusr
  oewmctcxjqhzhgmdylfapviusr
  oewmbtcyjqnzhmkdylfarviusr
  oewmbtcxjqnzhgkdpnfzpviusr
  oewmptcxjqnzhgkdylkapviulr
  nefmbtcxsqnzhgkdylfapviusr
  oewmbtcxwqnzhgkdilfapvizsr
  eewmbtcxjqwzhghdylfapviusr
  oewmbtixmqnzhgkjylfapviusr
  okwmbtcdzqnzhgkdylfapviusr
  oewmbtxxjrnzigkdylfapviusr
  oewmdycxjqnzhekdylfapviusr
  oewmutcxjqnzhgkdylfapsiuqr
  oewmbacxjqnzrgkdrlfapviusr
  oewmbtcxpqnzhmkdylfapciusr
  oewabtcxjqnzhgkdyrcapviusr
  oswmbtcxjqnzhgkdrxfapviusr
  gewmbtcnjqnzhgkdylvapviusr
  newmbtcxjwnzfgkdylfapviusr
  lewmbtcxjqnzhgkdylfaptiujr
  oewwbtcxjqndhgkdylfapiiusr
  oewmbtcxjqnzhggdylfapvqmsr
  lewmbtcxjqnzhgkhllfapviusr
  oewmbtocjqnzhgkdylfapvhusr
  oedmbtcxjqnzhgkdyhfapviusb
  oewmbtcxjqnzhgkdylfajvaosr
  zewmbtcxjqnzhgkdylfapvsssr
  oewmbthxjqnzhskdylfapviuqr
  yewmrtcvjqnzhgkdylfapviusr
  oewmbtctjqnzhgkdylfabvhusr
  oesmstcxjqnzhgkdylfapqiusr
  oewmbtcxjqnzzgkdylfopiiusr
  otwmbtzxjqnzhgkdylfaxviusr
  ouwmbxcxjqnzhgkdylfapvnusr
  oewmbtcxjqezhgedylfapvsusr
  oesmhtcsjqnzhgkdylfapviusr
  oewdbtcxjqnzhgkdilfapvifsr
  oewmbtcxjqnzhgudynfamviusr
  qewhbtcxjqnzhgkdyxfapviusr
  oewmbzcxjqtzhgkdylfapvitsr
  oewmbtccjqzzhgkaylfapviusr
  jewmbtcxmqnzhlkdylfapviusr
  oewmbtcxjqbzhgkdnlfapviusp
  oeimbtcdjqnzhgkdylfapviuer
  oewtbtcxjqnihgkdylfahviusr
  oewmbtcxhqnzhgkdylfapdiudr
  oefmbtcxjqyshgkdylfapviusr
  oewmbtcxjqnzhgkfglfapviusx
  oecmbocxjqnzhgkdmlfapviusr
  oewmbtcxjqnzhghdylfavviuhr
  oewmbmcxiqnzhgkpylfapviusr
  oewmbtcnjqnzhgkrylfanviusr
  oewmbocxjqnzhzkdllfapviusr
  eewmbtckjqnzhgkdylfapviusg
  oewmbtcrjqqzhgkdylfapvigsr
  oewmbtcxjqazhgfdylfapjiusr
  oetmbtcxjqnzhgldylfapviqsr
  oewbbtcxjqnzlgkdylfapviuse
  oewmbtcxjqnzhglbolfapviusr
  oewmbtcxjqnzcgkdylfapviuhy
  oelmbtcxjqfzhgkdylaapviusr
  oojmbycxjqnzhgkdylfapviusr
  oewmbtrxjqnrhgkdylfapniusr
  oewmbtcxjqnzhgkyyhfapviuso
  oewabtcxjqnzhskdylfapviusx
  oewmbtcrjqnmhgkdylfapvnusr
  oewmbtcxjqrzhgkdylfapvpuss
  oewmbtcxhqnzwgkddlfapviusr
  kewmbtcxjqnzhgkyylfajviusr
  oswmbtcxjqnzhgkdjlfapviuss
  onwmbtcxjqnchgkdylfapvpusr
  oeymbtcxjqnxhikdylfapviusr
  oewmblcdjqnzhgkdylfapviysr
  oewmbtcxeqczhgudylfapviusr
  oewmbpgxjqnzhgkdylfapfiusr
  ohwmwtcxjqnzhgkdylftpviusr
  zebmbtuxjqnzhgkdylfapviusr
  `;
  console.log(findBoxes(replaceLR(expl)));